### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by knzudgt** [JangoSteve/remotipart#180]
I am wondering: does the gem work in Rails 5?
The readme file speaks about and focus on Rails 3.0, Rails 3.1 and Rails 4
My impression is that the README.rdoc file is outdated (dating back to 5 years ago) and would need an update.

**Comment by Onidzuka** [comment]
+1

**Comment by masudhossain** [comment]
I don't think it works for rails 5, yet. Which is a bummer since literally everyone switched over to it for ActionCables. Was really hoping to use Remotipart + actioncables for real time files like Dropbox.

**Comment by madeindjs** [comment]
It work on Rails 5.0.1 but  callback is catched by `ajax:error` (and not `ajax:remotipartComplete` and `ajax:error` as written in documentation..)

**Comment by knzudgt** [comment]
@madeindjs I tested it in Rails 5.0.0.1 and it seems working

**Comment by JPedroMarques** [comment]
It works in Rails 5.0.1, but it does have an error int the js file.

Uncaught TypeError: t.rails.ajax(...).complete is not a function
  at HTMLFormElement.<anonymous> (jquery.remotipart.js:54)
  ...

**Comment by mshibuya** [comment]
Done by 88d9a7d55bde66acb6cf3a3c6036a5a1fc991d5e.
